
---
# This playbook installs control node software

# Install Docker
# yum update -y
# yum install -y docker
# service docker start
# usermod -a -G docker ec2-user
# chkconfig docker on

- name: Install Docker
  yum: name={{ item }} state=present
  with_items:
   - docker
  become: yes
  tags:
    - control

- name: Setting Docker service state
  service: name=docker enabled=yes state=started
  become: yes
  tags:
    - control

- name: Download MID software
  become: yes 
  command: wget --progress=bar:force --no-check-certificate {{mid_url}} -O /root/mid.rpm
  tags:
    - control

- name: Install MID software
  become: yes
  shell: |
    RPM=/root/mid.rpm
    PACKAGE=$(rpm -qp $RPM)
    if [ ! $(rpm -q $PACKAGE) ]; then
      rpm -ivh --nodeps $RPM
    fi
  tags:
    - control    