---
# This playbook installs ACC software

- name: Download ACC software
  become: yes
  command: wget --progress=bar:force --no-check-certificate {{acc_url}} -O /root/acc.rpm
  tags:
    - acc

- name: Install ACC software
  become: yes
  shell: |
    RPM=/root/acc.rpm
    PACKAGE=$(rpm -qp $RPM)
    if [[ ! $( rpm -qa $PACKAGE ) =~ ${PACKAGE} ]]
    then
      rpm -ivh --nodeps $RPM
    fi
    
  tags:
    - acc