---
# This playbook installs ACC software

- name: Download ACC software
  command: wget --progress=bar:force --no-check-certificate {{acc_url}} -O acc.rpm
  become: yes 
  tags:
    - acc

- name: Install ACC software
  command: rpm -ivh --nodeps acc.rpm
  become: yes  
  tags:
    - acc