---
# This playbook contains common plays that will be run on all spring nodes.

- name: Install Java OpenJDK 11
  command: amazon-linux-extras install java-openjdk11 -y
  become: yes
  tags:
    - spring