---
# This playbook installs filebeat software

- name: Configure Filebeat for MySQL
  become: yes
  shell: |
    # Configure Filebeat
    cat << EOF > /etc/filebeat/filebeat.yml
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/mariadb/mariadb.log
      fields:
        sn-application: Pet Clinic
        sn-service: mysql
        sn-sourcetype: mariadb-error
      ignore_older: 6h
    - type: log
      enabled: true
      paths:
        - /var/log/mariadb/all.log
      fields:
        sn-application: Pet Clinic
        sn-service: mysql
        sn-sourcetype: mariadb-sql
      ignore_older: 6h
    - type: log
      enabled: true
      paths:
        - /var/log/messages
      fields:
        sn-application: Pet Clinic
        sn-service: syslog
        sn-sourcetype: syslog-messages
      ignore_older: 6h        
    output.logstash:
      enabled: true
      slow_start: true
      #to stream over ssl with custom mid certificate please uncomment the following line:
      #ssl.certificate_authorities: ["PATH_TO_CERTIFICATE_AUTHORITY"]
      ssl.enabled: true
      #to stream over ssl with custom mid certificate please comment out the following line:
      ssl.verification_mode: "none"
      hosts: ["{{mysql_logstash}}"]
    logging.level: info
    logging.to_files: true
    logging.files:
      path: /var/log/filebeat
      name: filebeat.log
      keepfiles: 7
      permissions: 0644      
    EOF

    # Restart Filebeat
    systemctl restart filebeat
    
  tags:
    - filebeat-spring