# This playbook installs MySQL

- name: Install MySQL
  yum: name={{ item }} state=present
  with_items:
   - mariadb-server
  become: yes

- name: mariadb service state
  service: name=mariadb enabled=yes state=started
  become: yes