---
# This playbook installs MySQL

- name: Install MySQL
  become: yes
  yum: name={{ item }} state=present
  with_items:
   - mariadb-server
  tags:
    - mysql  

- name: Set MariaDB service state
  become: yes
  service: name=mariadb enabled=yes state=started
  tags:
    - mysql
   
- name: Install PyMySQL
  become: yes
  pip:
    name: pymysql
    state: present
  tags:
    - mysql      

- name: Configure Logging Properties
  become: yes
  shell: |
    # Set Logging Properties
    mkdir -p /etc/my.cnf.d
    cat <<-EOF > /etc/my.cnf.d/my.cnf
    [mysqld]
    general_log_file = /var/log/mariadb/all.log
    general_log = 1
    EOF

    # Restart MySQL
    systemctl daemon-reload
    systemctl restart mariadb

  tags:
    - mysql

- name: Unset Limits
  become: yes
  shell: |
    # Unset Limits
    mkdir -p /etc/systemd/system/mariadb.service.d
    cat <<-EOF > /etc/systemd/system/mariadb.service.d/limits.conf  
    [Service]
    LimitNOFILE=infinite
    EOF

    # Restart MySQL
    systemctl daemon-reload
    systemctl restart mariadb

  tags:
    - mysql

- name: Configure PetClinic Database
  become: yes
  community.mysql.mysql_query:
    query:
    - CREATE DATABASE IF NOT EXISTS petclinic;
    - ALTER DATABASE petclinic DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
    - GRANT ALL PRIVILEGES ON petclinic.* TO 'petclinic'@'%' IDENTIFIED BY 'petclinic';
    - GRANT ALL ON *.* TO ''@'localhost';
    - FLUSH PRIVILEGES;
    single_transaction: yes
  tags:
    - mysql  