---
# This playbook installs MySQL

- name: Install MySQL
  yum: name={{ item }} state=present
  with_items:
   - mariadb-server
  become: yes
  tags:
    - mysql  

- name: Set MariaDB service state
  service: name=mariadb enabled=yes state=started
  become: yes
  tags:
    - mysql
   
- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
  become: yes
  tags:
    - mysql      

- name: Configure Logging Properties
  community.mysql.mysql_query:
    query:
    - SET GLOBAL general_log = 'ON';
    - SET GLOBAL general_log_file = '/var/log/mariadb/all.log';
    single_transaction: yes
  become: yes
  tags:
    - mysql

- name: Configure PetClinic Database
  community.mysql.mysql_query:
    query:
    - CREATE DATABASE IF NOT EXISTS petclinic;
    - ALTER DATABASE petclinic DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
    - GRANT ALL PRIVILEGES ON petclinic.* TO 'petclinic'@'%' IDENTIFIED BY 'petclinic';
    - FLUSH PRIVILEGES;
    single_transaction: yes
  become: yes
  tags:
    - mysql  