---
# This playbook installs MySQL

- name: Installing MySQL
  yum: name={{ item }} state=present
  with_items:
   - mariadb-server
  become: yes
  tags:
    - mysql  

- name: Setting MariaDB service state
  service: name=mariadb enabled=yes state=started
  become: yes
  tags:
    - mysql

# Run Install Script
# mysql -u root <<EOF
# DROP USER ''@'localhost';
# CREATE DATABASE IF NOT EXISTS petclinic;
# ALTER DATABASE petclinic
#   DEFAULT CHARACTER SET utf8
#   DEFAULT COLLATE utf8_general_ci;
#   GRANT ALL PRIVILEGES ON petclinic.* TO 'petclinic'@'%' IDENTIFIED BY 'petclinic';
# FLUSH PRIVILEGES;
# EXIT;
# EOF