---
# This playbook installs MySQL

- name: Install MySQL
  yum: name={{ item }} state=present
  with_items:
   - mariadb-server
  become: yes
  tags:
    - mysql  

- name: Set MariaDB service state
  service: name=mariadb enabled=yes state=started
  become: yes
  tags:
    - mysql
   
- name: Installing PyMySQL
  pip:
    name: PyMySQL
    executable: pip3
  tags:
    - mysql       

# - name: Configuring the PetClinic Database
#   community.mysql.mysql_query:
#     login_user: root
#     query:
#     - CREATE DATABASE IF NOT EXISTS petclinic;
#     single_transaction: yes
#   tags:
#     - mysql       

# Run Install Script
# mysql -u root <<EOF
# DROP USER ''@'localhost';
# CREATE DATABASE IF NOT EXISTS petclinic;
# ALTER DATABASE petclinic
#   DEFAULT CHARACTER SET utf8
#   DEFAULT COLLATE utf8_general_ci;
#   GRANT ALL PRIVILEGES ON petclinic.* TO 'petclinic'@'%' IDENTIFIED BY 'petclinic';
# FLUSH PRIVILEGES;
# EXIT;
# EOF