---
# This playbook deploys the whole application stack in this site.

- name: Applying common software to all nodes
  hosts: all
  remote_user: ec2-user

  roles:
    - common

- name: Install control node(s) software
  hosts: control
  remote_user: ec2-user

  roles:
    - control       

- name: Install NGINX node(s) software
  hosts: nginx
  remote_user: ec2-user

  roles:
    - nginx

- name: Install Java Spring Boot node(s) software
  hosts: spring
  remote_user: ec2-user

  roles:
    - spring

- name: Install MySQL Database node(s) software
  hosts: mysql
  remote_user: ec2-user

  roles:
    - mysql    